# Generated by Django 4.2.28 on 2026-03-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0054_namespace_tenant'),
        ('nautobot_routing_tables', '0002_auto_20260312_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingtable',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_tables', to='ipam.vrf'),
        ),
        migrations.AddConstraint(
            model_name='routingtable',
            constraint=models.UniqueConstraint(condition=models.Q(('vrf__isnull', True)), fields=('device',), name='unique_global_routing_table_per_device'),
        ),
    ]
