# Generated by Django 4.2.26 on 2026-04-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nautobot_routing_tables', '0002_routing_table_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routingprotocol',
            options={'ordering': ('routing_table__device__name', 'routing_table__vrf__name', 'protocol'), 'verbose_name': 'Routing Protocol Override', 'verbose_name_plural': 'Routing Protocol Overrides'},
        ),
        migrations.AlterField(
            model_name='route',
            name='next_hop_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'ipam'), ('model__in', ('ipaddress', 'prefix'))), models.Q(('app_label', 'dcim'), ('model__in', ('interface',))), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='route',
            name='protocol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='routingprotocol',
            name='protocol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='routingprotocol',
            name='routing_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_overrides', to='nautobot_routing_tables.routingtable'),
        ),
    ]
