# Generated by Django 4.2.27 on 2026-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_routing_tables", "0004_repair_legacy_schema"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                condition=models.Q(("next_hop_id__isnull", True), ("next_hop_type__isnull", True)),
                fields=("routing_table", "prefix", "protocol"),
                name="unique_route_without_next_hop",
            ),
        ),
    ]
